project:
  type: website
  output-dir: docs

website:
  title: "yscheryl.github.io"
  navbar:
    left:
      - href: characteristics1.qmd
        text: Home
      - href: datastory1.qmd
        text: Data Story

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

